[tool.poetry]
name = "yolo"
version = "0.1.0"
description = ""
authors = ["Brian Thorne <brian@thorne.link>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
openai = "^0.27.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

